### ISSUE TITLE
Insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by cdrw700** [ETCDEVTeam/emerald-wallet#761]
Hello, my wallet has some ETC in it. I want to send some, I click on MAX and Ok, and then I have this bug.

By the way there is still an old transaction in queue. I don't know why. I haved added ETC to this wallet since so there are some ETC in this wallet. It's not like i'm trying to send nothing..

``` 
JsonRpcError: Insufficient funds for gas * price + value
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/maxim/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:23949:30)
    at new JsonRpcError (file:///C:/Users/maxim/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:23978:116)
    at file:///C:/Users/maxim/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:24015:19
    at <anonymous>
 ```

**Comment by BelfordZ** [comment]
Proper solution to this problem is to estimate gas before each transaction, and to check the gas price right before doing max calculation. 

To further prevent this from happening, it is be advisable to use exponential backoff retries on the whole thin. Optionally, we could optimistically update the UI, with notification of error after the fact if  applicable.
